name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Python Linter
      run: |
          python -m pip install --upgrade pip
          pip install black[d]
          black .
          
          python3 main.py
